# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

NNM_fit <- function(M, mask, L_init, u_init, v_init, to_estimate_u, to_estimate_v, lambda_L, niter = 1000L, rel_tol = 1e-5, is_quiet = 1L) {
    .Call('_MCPanel_NNM_fit', PACKAGE = 'MCPanel', M, mask, L_init, u_init, v_init, to_estimate_u, to_estimate_v, lambda_L, niter, rel_tol, is_quiet)
}

NNM <- function(M, mask, to_estimate_u, to_estimate_v, lambda_L, niter = 1000L, rel_tol = 1e-5, is_quiet = 1L) {
    .Call('_MCPanel_NNM', PACKAGE = 'MCPanel', M, mask, to_estimate_u, to_estimate_v, lambda_L, niter, rel_tol, is_quiet)
}

NNM_CV <- function(M, mask, to_estimate_u, to_estimate_v, num_lam, niter = 1000L, rel_tol = 1e-5, cv_ratio = 0.6, num_folds = 5L, is_quiet = 1L) {
    .Call('_MCPanel_NNM_CV', PACKAGE = 'MCPanel', M, mask, to_estimate_u, to_estimate_v, num_lam, niter, rel_tol, cv_ratio, num_folds, is_quiet)
}

